### PR TITLE
Fix default values are removed on serialization 

### LINKED ISSUE #129: Properties with with default value are not been serialized when the current value is equal to its default value
**What would you like to be added**:

```

 
    const workflow: Specification.Workflow = workflowBuilder()
      .id('helloworld')
      .version('1.0')
      .specVersion('0.7')
      .name('Hello World Workflow')
      .description('Inject Hello World')
      .start('Hello State')
      .states([
        injectstateBuilder()
          .name('Hello State')
          .data({
            'result': 'Hello World!'
          })
          .usedForCompensation(false) // <-- this is not been serialized
          .build()
      ])
      .build();
    
    //Actual behaviour
    expect(Workflow.toYaml(workflow)).toBe('id: helloworld\n' +
      'version: \'1.0\'\n' +
      'specVersion: \'0.7\'\n' +
      'name: Hello World Workflow\n' +
      'description: Inject Hello World\n' +
      'start: Hello State\n' +
      'states:\n' +
      '  - type: inject\n' +
      '    name: Hello State\n' +
      '    data:\n' +
      '      result: Hello World!\n' +
      '    end: true\n');
    
    //Expected behaviour
    expect(Workflow.toYaml(workflow)).toBe('id: helloworld\n' +
      'version: \'1.0\'\n' +
      'specVersion: \'0.7\'\n' +
      'name: Hello World Workflow\n' +
      'description: Inject Hello World\n' +
      'start: Hello State\n' +
      'states:\n' +
      '  - type: inject\n' +
      '    usedForCompensation: false' + // <-- here
      '    name: Hello State\n' +
      '    data:\n' +
      '      result: Hello World!\n' +
      '    end: true\n');
```
    

**Why is this needed**:

### PR DESCRIPTION
**Pull request by antmendoza**
**Many thanks for submitting your Pull Request :heart:!**

**What this PR does / why we need it**:
closes #129 

**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

File: src/lib/definitions/eventdef.ts [hunk 1]
```diff
@@ -14,11 +14,21 @@
...
+  cleanSourceModelProperty,
+  normalizeDataOnly,
+  normalizeKind,
+  overwriteCorrelation,
+  overwriteMetadata,
+} from './utils';
 import { CorrelationDefs } from './types';
 
 export class Eventdef {
+  sourceModel?: Eventdef;
```
Comment (antmendoza) [inline src/lib/definitions/eventdef.ts:27]: The main change is this. I have created new property `sourceModel` to store the original value and removed it in the normalize method https://github.com/serverlessworkflow/sdk-typescript/pull/156/files#diff-d777c6a12a20ec15dd1884f631d697c0a39b4ac3d6ed1344786a33d6628325d5R82 before serialization

Having the source stored we can infer if the property has been set by the user or by us in the constructor.  https://github.com/serverlessworkflow/sdk-typescript/pull/156/files#diff-85a746dfd50b2ed38f2af0732b08ec5e2c76325048e9d6ae857a12120cda0361R708

**Review by tsurdilo — APPROVED** [review]
