### PR TITLE
fix example test

### LINKED ISSUE #88: Fix test/examples code
**What would you like to be added**:

Fix test/examples code to run with the actual code 

**Why is this needed**:

### PR DESCRIPTION
**Pull request by antmendoza**
**Many thanks for submitting your Pull Request :heart:!**

fix example test

closes #88 

**What this PR does / why we need it**:

**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Review by tsurdilo — APPROVED** [review]

File: src/lib/builders/foreachstate-builder.ts [hunk 1]
```diff
@@ -28,6 +28,10 @@ import { validators } from '../validators';
 function foreachstateBuildingFn(data: Specification.Foreachstate): () => Specification.Foreachstate {
   return () => {
     data.type = 'foreach';
+
+    //FIXME https://github.com/serverlessworkflow/sdk-typescript/issues/95
+
+    data.usedForCompensation = false;
```
Comment (JBBianchi) [inline src/lib/builders/foreachstate-builder.ts:34]: IMO this is wrong on 2 levels:

- Codewise, this **always** sets `usedForCompensation` to `false`. So even if someone intentionally sets it to `true`, it will be overridden.
- Schemawise this is not what the JSON Schema says so it's an opiniated choice to "default" this value to `false`.

File: tests/examples/applicantrequest.spec.ts [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+                refName: 'sendRejectionEmailFunction',
+                arguments: { applicant: '${ .applicant }' },
+              })
+              .build(),
+          ])
+          .build(),
+      ])
+      .build();
+
+    const expected = JSON.parse(fs.readFileSync('./tests/examples/applicantrequest.json', 'utf8'));
```
Comment (JBBianchi) [inline tests/examples/applicantrequest.spec.ts:75]: Please prefere the `require` method:

```typescript
//...
import expected from './applicantrequest.json';

describe('applicationrequest workflow example', () => {
//...
    expect(workflow).toEqual(expected as any);
// ...
});
```

File: tests/examples/booklending.spec.ts [hunk 3]
```diff
@@ -0,0 +1,149 @@
...
+  it('should generate Workflow object', function () {
+    const workflow = workflowBuilder()
+      .id('booklending')
+      .name('Book Lending Workflow')
+      .version('1.0')
+      .start('Book Lending Request')
+      .states([
+        eventstateBuilder()
+          .name('Book Lending Request')
+          .onEvents([oneventsBuilder().eventRefs(['Book Lending Request Event']).build()])
```
Comment (JBBianchi) [inline tests/examples/booklending.spec.ts:41]: You don't need to fix but for futur work, I think it's better to stay consistant and always put the setters/build on a new line:

```typescript
.onEvents([
  oneventsBuilder()
    .eventRefs(['Book Lending Request Event'])
    .build()
  ])
```

File: tools/generate-builders.ts [hunk 4]
```diff
@@ -64,7 +64,9 @@ const buildersExtensions: { [key: string]: BuilderExtension } = {
     preValidate: `\r\n    data.type = 'event';`,
   },
   Foreachstate: {
-    preValidate: `\r\n    data.type = 'foreach';`,
+    preValidate: `\r\n    data.type = 'foreach';
+                  \r\n    //FIXME https://github.com/serverlessworkflow/sdk-typescript/issues/95
+                  \r\n    data.usedForCompensation = false;`,
```
Comment (JBBianchi) [inline tools/generate-builders.ts:69]: See related comment on the generated file.

**Review by JBBianchi — COMMENTED** [review]
Nice and massive work @antmendoza !

Just found 1 bug, 1 improvement and 1 remark.

File: src/lib/builders/foreachstate-builder.ts (hunk 1 above)
Comment (JBBianchi) [reply src/lib/builders/foreachstate-builder.ts:34]: I take back what I said about the schema, it does indeed specify a default.

The proper way to check would then be:
```typescript
data.usedForCompensation = data.usedForCompensation || false;
```
